name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  examples:
    name: Examples
    runs-on: python:3.11.4-buster

    env:
      DEVITO_COMPILER: gcc
      DEVITO_LANGUAGE: "openmp"
      PYTHON_VERSION: "3.11.3"

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

    steps:
    - name: Checkout stride
      uses: actions/checkout@v2
      with:
        repository: trustimaging/stride
        path: "stride"

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: stride
        environment-file: "stride/environment.yml"
        python-version: 3.11.3
        auto-activate-base: false

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        cd stride
        pip install -e .

    - name: Homogeneous examples
      shell: bash -l {0}
      run: |
        cd stride
        mrun -nw 1 -nth 2 python stride_examples/examples/homogeneous_acoustic/forward_2D.py
        mrun -nw 1 -nth 2 python stride_examples/examples/homogeneous_acoustic/forward_3D.py
        mrun -nw 1 -nth 2 python stride_examples/examples/homogeneous_elastic/forward_2D.py
    - name: Breast 2D
      shell: bash -l {0}
      run: |
        cd stride
        mrun -nw 1 -nth 2 python stride_examples/examples/breast2D/01_script_forward.py
        mrun -nw 1 -nth 2 python stride_examples/examples/breast2D/02_script_inverse.py
